# Generated by Django 4.1 on 2022-08-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_score_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='seconds',
            field=models.IntegerField(null=True),
        ),
    ]
