# Generated by Django 4.1 on 2022-08-08 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_score_hours_score_minutes_score_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='time',
        ),
    ]
