# Generated by Django 4.1 on 2022-08-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_score_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='enemy_spawn_factor',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='enemy_speed',
            field=models.FloatField(null=True),
        ),
    ]
