# Generated by Django 4.1 on 2022-08-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_score_enemy_spawn_factor_score_enemy_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_enemy_speed', models.FloatField()),
                ('starting_enemy_spawn_factor', models.FloatField()),
                ('enemy_speed_incremental_factor', models.FloatField()),
                ('enemy_spawn_incremental_factor', models.FloatField()),
            ],
        ),
    ]
