# Generated by Django 4.1 on 2022-08-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
