# Generated by Django 4.1 on 2022-08-08 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_difficulty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.difficulty'),
        ),
    ]
